# Generated by Django 5.1.4 on 2025-01-16 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_personnevulnerable_age_personnevulnerable_revenu'),
    ]

