# Generated by Django 5.1.4 on 2025-01-19 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_personnevulnerable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnevulnerable',
            name='entite',
            field=models.CharField(choices=[('femme_enceinte', 'Femme Enceinte'), ('enfants_handicapes', 'Enfants Handicapés'), ('enfants_de_la_rue', 'Enfants de la Rue'), ('autres', 'Autres')], default='autres', max_length=50),
        ),

    ]
