# Generated by Django 5.1.4 on 2025-01-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_personnevulnerable_entite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnevulnerable',
            name='entite',
            field=models.CharField(choices=[('femme_enceinte', 'Femmes Enceintes'), ('enfants_handicapes', 'Enfants Handicapés'), ('enfants_de_la_rue', 'Enfants de la Rue'), ('autres', 'Autres')], default='autres', max_length=50),
        ),
    ]
