# Generated by Django 5.1.4 on 2025-01-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_personnevulnerable_entite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_recenseur',
            field=models.BooleanField(default=False),
        ),
    ]
