# Generated by Django 5.1.4 on 2025-01-26 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_recenseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnevulnerable',
            name='recenseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnes_recensees', to=settings.AUTH_USER_MODEL),
        ),
    ]
