# Generated by Django 5.1.4 on 2025-01-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_personnevulnerable_recenseur'),
    ]

