# Generated by Django 5.1.4 on 2025-01-26 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_personnevulnerable_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnevulnerable',
            name='montant_recu',
        ),

        migrations.AlterField(
            model_name='personnevulnerable',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personnevulnerable',
            name='est_vulnerable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personnevulnerable',
            name='recenseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recensement', to=settings.AUTH_USER_MODEL),
        ),

    ]
