# Generated by Django 5.1.4 on 2025-01-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_personnevulnerable_montant_recu_and_more'),
    ]


