# Generated by Django 5.1.4 on 2025-01-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_personnevulnerable_revenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnevulnerable',
            name='revenu',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
