# Generated by Django 5.1.4 on 2025-01-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_personnevulnerable_revenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnevulnerable',
            name='recenseur',
        ),
        migrations.AddField(
            model_name='personnevulnerable',
            name='montant_recu',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='personnevulnerable',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personnevulnerable',
            name='est_vulnerable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='personnevulnerable',
            name='revenu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
