# Generated by Django 5.1.4 on 2025-01-27 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_personnevulnerable_recenseur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnevulnerable',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
