# Generated by Django 5.1.4 on 2025-01-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_personnevulnerable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnevulnerable',
            name='first_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='personnevulnerable',
            name='last_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='personnevulnerable',
            name='validated_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personnevulnerable',
            name='est_vulnerable',
            field=models.BooleanField(default=False),
        ),
    ]
