# Generated by Django 5.1.4 on 2025-01-28 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_personnevulnerable_recenseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnevulnerable',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='personnevulnerable',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='personnevulnerable',
            name='validated_by_admin',
        ),
        migrations.AlterField(
            model_name='personnevulnerable',
            name='recenseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnes_recensees', to=settings.AUTH_USER_MODEL, verbose_name='Recenseur'),
        ),
    ]
