# Generated by Django 5.1.4 on 2025-01-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_personnevulnerable_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnevulnerable',
            name='first_name',
            field=models.CharField(default=' ', max_length=150, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='personnevulnerable',
            name='last_name',
            field=models.CharField(default=' ', max_length=150, verbose_name='Nom'),
        ),
    ]
