# Generated by Django 5.1.4 on 2025-01-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_personnevulnerable_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnevulnerable',
            name='validated_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
