# Generated by Django 5.1.4 on 2025-01-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_personnevulnerable_validated_by_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnevulnerable',
            name='validated_by_admin',
        ),
    ]
