# Generated by Django 5.1.4 on 2025-01-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_personnevulnerable_validated_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnevulnerable',
            name='validated_by_admin',
            field=models.BooleanField(default=False, verbose_name="Validé par l'administrateur"),
        ),
        migrations.AlterField(
            model_name='personnevulnerable',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='personnevulnerable',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
    ]
