# Generated by Django 5.1.4 on 2025-01-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_personnevulnerable_validated_by_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnevulnerable',
            name='lat',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='personnevulnerable',
            name='lon',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='personnevulnerable',
            name='region_geographique',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Région géographique'),
        ),
    ]
