# Generated by Django 5.1.4 on 2025-02-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_personnevulnerable_lat_personnevulnerable_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnevulnerable',
            name='sexe',
            field=models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='homme', max_length=10),
        ),
    ]
