# Generated by Django 5.1.4 on 2025-02-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_personnevulnerable_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnevulnerable',
            name='sexe',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Hemme', 'Femme')], default='homme', max_length=10),
        ),
    ]
