# Generated by Django 5.1.4 on 2025-02-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_personnevulnerable_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnevulnerable',
            name='nombre_enfants',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'enfants"),
        ),
    ]
