# Generated by Django 5.1.4 on 2025-02-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_personnevulnerable_nombre_enfants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnevulnerable',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='personnevulnerable',
            name='lon',
        ),
    ]
