# Generated by Django 5.1.4 on 2025-02-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_personnevulnerable_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnevulnerable',
            name='region_geographique',
            field=models.CharField(blank=True, choices=[('Agnéby', 'Agnéby'), ('Bafing', 'Bafing'), ('Bas-Sassandra', 'Bas-Sassandra'), ('Denguélé', 'Denguélé'), ('District des Montagnes', 'District des Montagnes'), ('Fromager', 'Fromager'), ('Haut-Sassandra', 'Haut-Sassandra'), ('Lacs', 'Lacs'), ('Lagunes', 'Lagunes'), ('Marahoué', 'Marahoué'), ('Moyen-Cavally', 'Moyen-Cavally'), ('Moyen-Comoé', 'Moyen-Comoé'), ('N’zi-Comoé', 'N’zi-Comoé'), ('Région du Sud-Comoé', 'Région du Sud-Comoé'), ('Savanes', 'Savanes'), ('Sud-Bandama', 'Sud-Bandama'), ('Vallée du Bandama', 'Vallée du Bandama'), ('Worodougou', 'Worodougou'), ('Zanzan', 'Zanzan')], max_length=100, null=True, verbose_name='Région géographique'),
        ),
        migrations.AlterField(
            model_name='personnevulnerable',
            name='sexe',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=5),
        ),
    ]
