# Generated by Django 5.1.4 on 2025-03-11 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_personnevulnerable_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnevulnerable',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnevulnerable', to=settings.AUTH_USER_MODEL),
        ),
    ]
