# Generated by Django 5.1.4 on 2025-03-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_personnevulnerable_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
