# Generated by Django 5.1.4 on 2025-05-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnevulnerable',
            name='analyse_llm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personnevulnerable',
            name='categorie_predite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personnevulnerable',
            name='niveau_pauvrete',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
