# Generated by Django 5.1.4 on 2025-06-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_personnevulnerable_analyse_llm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnevulnerable',
            name='documents_info',
            field=models.JSONField(blank=True, default=list, verbose_name='Informations des documents'),
        ),
        migrations.AddField(
            model_name='personnevulnerable',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_recensement/', verbose_name='Photo de profil'),
        ),
    ]
