# Generated by Django 5.1.4 on 2025-06-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_personnevulnerable_documents_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnevulnerable',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='documents_recensement/', verbose_name='Document principal'),
        ),
    ]
