# Generated by Django 5.1.4 on 2025-06-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_personnevulnerable_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnevulnerable',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='personnevulnerable',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
