# Generated by Django 5.1.4 on 2025-06-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_personnevulnerable_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnevulnerable',
            name='entite',
            field=models.CharField(choices=[('orphelin', 'Orphelin'), ('veuve', 'Veuve'), ('handicape', 'Handicapé'), ('senior', 'Senior'), ('refugie', 'Réfugié'), ('sans_abri', 'Sans Abri'), ('famille_nombreuse', 'Famille Nombreuse'), ('chomeur', 'Chômeur'), ('malade_chronique', 'Malade Chronique'), ('etudiant_precaire', 'Étudiant Précaire')], default='autres', max_length=50),
        ),
    ]
