# Generated by Django 5.1.4 on 2025-01-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_don', models.DateTimeField(auto_now_add=True)),
                ('est_reparti', models.BooleanField(default=False)),
            ],
        ),
    ]
