# Generated by Django 5.1.4 on 2025-01-14 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='donateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='don',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons_recus', to='users.personnevulnerable'),
        ),
    ]
