# Generated by Django 5.1.4 on 2025-01-19 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
        ('users', '0003_alter_personnevulnerable_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='don',
            name='personne',
        ),
        migrations.AddField(
            model_name='don',
            name='description',
            field=models.TextField(default='Aucune description'),
        ),
        migrations.AddField(
            model_name='don',
            name='entite_vulnerable',
            field=models.CharField(default='femme_enceinte', max_length=100),
        ),
        migrations.AddField(
            model_name='don',
            name='est_valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='don',
            name='personne_vulnerable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.personnevulnerable'),
        ),
        migrations.AddField(
            model_name='don',
            name='provenance',
            field=models.CharField(default='source1', max_length=100),
        ),
    ]
