# Generated by Django 5.1.4 on 2025-01-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_remove_don_personne_don_description_and_more'),
        ('users', '0003_alter_personnevulnerable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='nombre_personnes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='don',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='don',
            name='entite_vulnerable',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='don',
            name='personne_vulnerable',
        ),
        migrations.AlterField(
            model_name='don',
            name='provenance',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='don',
            name='personne_vulnerable',
            field=models.ManyToManyField(blank=True, related_name='dons', to='users.personnevulnerable'),
        ),
    ]
