# Generated by Django 5.1.4 on 2025-01-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_don_nombre_personnes_alter_don_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='est_retires',
            field=models.BooleanField(default=False),
        ),
    ]
