# Generated by Django 5.1.4 on 2025-06-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_don_est_retires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='don',
            name='nombre_personnes',
        ),
    ]
